### ISSUE TITLE
FYI: SeqFu supports IRIDA samplesheet

### ISSUE THREAD

**Issue by telatin** [phac-nml/irida-uploader#115]
Just to let you know that I added the "irida uploader" samplesheet in `SeqFu metadata`.

[SeqFu](https://telatin.github.io/seqfu2/) is a fast toolkit to manipulate/inspect FASTX files, and ships a metadata generator to generate blank samplesheets in multiple formats (like Qiime2).

Now supports IRIDA like this:
```
seqfu metadata -f irida  -P 1024 /path/to/reads
```

the output is like:
```
Sample_Name,Project_ID,File_Forward,File_Reverse
stripped,1024,stripped_R1.fq,stripped_R2.fq
test,1024,test_R1.fq,test_R2.fq
```

Best!

**Comment by JeffreyThiessen** [comment]
Awesome, I love to see support for IRIDA and our related tools. I have added `seqfu` as a parser alias for the simple `directory` parser #116 so it will be even more straightforward to use.
