### ISSUE TITLE
Allow Directory Parser to use full file paths, in addition to file names.

### ISSUE THREAD

**Issue by JeffreyThiessen** [phac-nml/irida-uploader#21]
Suggested by @happykhan 

Use case: Reads can sometimes be scattered around, so it would be nice to be able to just give the path directly in the SampleList.csv file.

Related code: `/parsers/directory/sample_parser.py` in `_parse_sample_list` search for `path.join`

**Comment by JeffreyThiessen** [comment]
A new test case should be added to the directory parser tests to ensure this functionality too.

**Comment by JeffreyThiessen** [comment]
Related code block in the same file:
```
        if sample_dict['File_Forward'] not in data_dir_file_list:
            raise exceptions.SampleSheetError(
                ("Your sample sheet is malformed. {} Does not match any file in the directory {}"
                 "".format(sample_dict['File_Forward'], data_dir)),
                sample_sheet_file
            )
        if paired_end_read and sample_dict['File_Reverse'] not in data_dir_file_list:
            raise exceptions.SampleSheetError(
                ("Your sample sheet is malformed. {} Does not match any file in the directory {}"
                 "".format(sample_dict['File_Reverse'], data_dir)),
                sample_sheet_file
            )
```

**Comment by happykhan** [comment]
![image](https://user-images.githubusercontent.com/1452696/54299803-88e9d880-45b3-11e9-89c5-a7c7ca0e64a9.png)

And it freaked out

![image](https://user-images.githubusercontent.com/1452696/54299875-af0f7880-45b3-11e9-9e81-1d5c51a15eeb.png)

It's fine if I remove the period at the end,

**Comment by happykhan** [comment]
Yup and the few lines below that.

`    # Add the dir to each file to create the full path
       # sample_dict['File_Forward'] = path.join(data_dir, sample_dict['File_Forward'])
        # if paired_end_read:
       #     sample_dict['File_Reverse'] = path.join(data_dir, sample_dict['File_Reverse'])`
