### ISSUE TITLE
Handle Read-Only Directories

### ISSUE THREAD

**Issue by JeffreyThiessen** [phac-nml/irida-uploader#24]
Use Case: 
When directories are archived or cannot be written to, we still may want to upload the data in them.

Current Functionality:
We have a catch all that stops the uploader from running on non writable directories.
We have multiple areas (9+) that use `os.W_OK` (write access ok) to check if the directory is accessable.

Potential Change
* Any use of `os.W_OK` should be changed to a read check, instead of a write check
* Have a new command line argument for doing a read-only (`-r` / `--readonly` ?) upload
* Code that writes to a file/directory (e.g. directory logging, status file) will have try/except blocks
  * If `-r` is set, do not attempt to write to the directory
  * if not `-r`, continue the upload, but print a warning to the user indicating the file could not be written
    * alternatively, fail to upload, and allow `--force` to bypass the error

**Comment by happykhan** [comment]
The new logging functionality does not hand read only dirs

When i run on a r only dir i get complaints from  add_log_to_directory(directory) when it tries to write a log there. Why can't logging file  be specified  as cli param (or just pipe to stdout)?

**Comment by happykhan** [comment]
Suggested fix (or similar)

```
def logging_start_block(directory):
    """
    Logs an information block to the console and file which indicates the start of an upload run.

    Includes the uploader version number set in the global_settings module
    :return:
    """
    if os.access(os.path.join(directory, 'irida-uploader.log'), os.W_OK):
        logger.add_log_to_directory(directory)
    logging.info("==================================================")
    logging.info("---------------STARTING UPLOAD RUN----------------")
    logging.info("Uploader Version {}".format(global_settings.UPLOADER_VERSION))
    logging.info("Logging to file in: " + global_settings.log_file)
    logging.info("==================================================")
```
