### ISSUE TITLE
Auto upload / directory monitor

### ISSUE THREAD

**Issue by JeffreyThiessen** [phac-nml/irida-uploader#6]
We should have a way to automatically upload when a run has completed sequencing and is ready for upload.

This may fit better as a shell script or cron job instead of a feature built into the uploader. More discussion is needed.

**Comment by JeffreyThiessen** [comment]
Building a `--all` command into the uploader that will upload all new runs found in a directory.
After uploading each run, it will check to see if there is a new run ready, and upload it.
Run status will be maintained through a json status file that resides in the run directory, this will be created/updated for every run that the uploader tries to upload.

This will allow cron or windows task scheduler to repeatedly run with the `--all` command to handle automatic uploads.

Runs that error out, or are invalid, will not attempt to be re-uploaded.

In addition, a `--force` command will also be added to bypass the above restriction, so failed runs can be reattempted without making the user edit/delete the status file.

Further functionality could include writing the IRIDA run id to the status file, so that a reupload could use the same run id, but this is outside the scope of this issue.

**Comment by JeffreyThiessen** [comment]
https://github.com/phac-nml/irida-uploader/tree/automated_uploads

**Comment by JeffreyThiessen** [comment]
a `--batch` option is being added that will allow a directory of runs to be uploaded all at once. This will allow a batch run to be scheduled with windows task scheduler, cron, or other similar software.

**Comment by tom114** [comment]
Was this completed in #30?  If so close this issue please.
