### ISSUE TITLE
Optional global configuration file

### ISSUE THREAD

**Issue by Takadonet** [phac-nml/irida-uploader#66]
## Describe your idea for a new feature
Nice to have an optional  global configuration file for sequencer that may have dozen of local users. It is time consuming for each individual user to create the same configuration file.

## Additional information
Add any other context, files, or screenshots about the feature request here.

**Comment by JeffreyThiessen** [comment]
Solution: Add a check to `config.py` that sees if there is a config file in the installation directory, then goes to user directory after.
